sgustjd2/YoriJori

- src/main/webapp/WEB-INF/cookingclass/NewFile.jsp
> cookingclass 폴더 하나 생성 - jsp 파일 하나 생성

- src/main/java/com/yorijori/foodcode/contoller/CookingclassController.java
- src/main/resources/static/common/classListShine.css
- src/main/resources/static/common/classListSlider.css
- src/main/webapp/WEB-INF/views/cookingclass/classList.jsp
css폴더가 안보여서 common에 넣었습니닷...!! 그 제가 뷰에 css링크 수정을 안해서 한번만 더올릴게유 ㄷ죄송해유
> 서소영 - 쿠킹클래스에 대한 컨트롤러 1, 뷰 1, css 2 추가

- src/main/java/com/yorijori/foodcode/contoller/CookingclassController.java
- src/main/java/com/yorijori/foodcode/contoller/RecipeController.java
- src/main/resources/static/common/css/cookingclass/classListShine.css
- src/main/resources/static/common/css/recipe/recipeInsert.css
- src/main/webapp/WEB-INF/views/cookingclass/classList.jsp
- src/main/webapp/WEB-INF/views/recipe/recipeInsert.jsp
> classinsert 생성

- src/main/resources/templates/thymeleaf/include/top.html
- src/main/resources/templates/thymeleaf/recipe/recipelist.html
- src/main/resources/templates/thymeleaf/recipe/recipeview.html
- 로그인 뷰 수정
- 닫기 수정
- 아이디 및 비밀번호 찾기 추가
> - 레시피 뷰 수정

- src/main/resources/static/common/css/board/read.css
- src/main/resources/static/common/css/board/reply.css
- src/main/resources/static/common/css/board/write.css
- src/main/resources/templates/thymeleaf/board/reply.html
- src/main/resources/templates/thymeleaf/board/write.html
- src/main/resources/templates/thymeleaf/member/signUpForm1.html
- src/main/resources/templates/thymeleaf/member/signUpForm2.html
- src/main/resources/templates/thymeleaf/member/signUpForm3.html
수정 좀 더 해서 저녁에 다시 한 번 보내겠습니다~!~!
> jquery css 수정 필요!!

- src/main/resources/static/common/css/board/list.css
- src/main/resources/static/common/css/board/read.css
- src/main/resources/static/common/css/board/reply.css
- src/main/resources/static/common/css/board/write.css
- src/main/resources/templates/thymeleaf/board/list.html
- src/main/resources/templates/thymeleaf/board/read.html
- src/main/resources/templates/thymeleaf/board/reply.html
- src/main/resources/templates/thymeleaf/board/write.html
- src/main/resources/templates/thymeleaf/member/signUpForm1.html
- src/main/resources/templates/thymeleaf/member/signUpForm2.html
- src/main/resources/templates/thymeleaf/member/signUpForm3.html
> 회원가입시 필요한 jquery 추가 전체적인 css 수정

- src/main/resources/application.properties
- src/main/resources/static/common/css/mypage/commentlist.css
- src/main/resources/static/common/js/customerService/CSpageNavigation.js
- src/main/resources/templates/thymeleaf/mypage/commentlist.html
- src/main/resources/templates/thymeleaf/mypage/recipelist.html
댓글 리스트 프론트 수정
-----------------------변경해야 할 사항--------------------------
checklist 하나만 선택할 수 있게 js 처리로 변경
> commentlist fixed

- src/main/resources/static/common/css/cookingclass/classListShine.css
- src/main/resources/static/common/css/cookingclass/classListSlider.css
- src/main/resources/static/common/css/customerService/inquiryForm_popup.css
- src/main/resources/templates/thymeleaf/cookingclass/classList.html
- src/main/resources/templates/thymeleaf/customerService/inquiry.html
- src/main/resources/templates/thymeleaf/customerService/inquiryForm_popup.html
- src/main/resources/templates/thymeleaf/recipe/recipeInsert.html
[레이아웃 이상한 페이지들 손보기, 문의폼 만들기, 문의폼 팝업]
> Other 레이아웃 수정, 문의

- pom.xml
- src/main/java/com/yorijori/foodcode/contoller/MemberController.java
- src/main/java/com/yorijori/foodcode/service/KakaoService.java
- src/main/resources/templates/thymeleaf/include/top.html
- 카카오 서비스단 추가
- 정보출력은 성공적이지만 아직 VIew단에 출력코드 추가안함
> - 카카오 로그인(테스트용) 추가

- src/main/java/com/yorijori/foodcode/controller/CookingclassController.java
- src/main/java/com/yorijori/foodcode/dto/CookingClassContentDTO.java
- src/main/java/com/yorijori/foodcode/dto/CookingClassCurriculum.java
- src/main/java/com/yorijori/foodcode/dto/CookingClassDTO.java
- src/main/java/com/yorijori/foodcode/dto/CookingClassFormDTO.java
- src/main/java/com/yorijori/foodcode/dto/CookingClassImageDTO.java
- src/main/java/com/yorijori/foodcode/dto/paymentDTO.java
- src/main/java/com/yorijori/foodcode/repository/CookingClassDAO.java
- src/main/java/com/yorijori/foodcode/repository/CookingClassDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/CookingClassService.java
- src/main/java/com/yorijori/foodcode/service/CookingClassServiceImpl.java
> DTO, service, DAO생성

- src/main/java/com/yorijori/foodcode/controller/MemberController.java
- src/main/java/com/yorijori/foodcode/jpa/entity/MemberEntity.java
- src/main/java/com/yorijori/foodcode/jpa/repository/MemberRepository.java
- src/main/java/com/yorijori/foodcode/service/LoginService.java
- src/main/resources/templates/thymeleaf/include/top.html
- src/main/resources/templates/thymeleaf/member/loginpage.html
- 프로필사진 변경은 추가안함
- 회원가입 기능 보류
- 계속오류남... insert는 되는데 오류페이지 계속떠서 떄려침
> - 로그인 기능추가

- src/main/java/com/yorijori/foodcode/controller/BoardController.java
- src/main/java/com/yorijori/foodcode/dto/BoardDTO.java
- src/main/java/com/yorijori/foodcode/jpa/repository/BoardRepository.java
- src/main/java/com/yorijori/foodcode/repository/BoardCommentDAO.java
- src/main/java/com/yorijori/foodcode/repository/BoardCommentDAOImpl.java
- src/main/java/com/yorijori/foodcode/repository/BoardDAO.java
- src/main/java/com/yorijori/foodcode/repository/BoardDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/BoardCommentService.java
- src/main/java/com/yorijori/foodcode/service/BoardCommentServiceImpl.java
- src/main/java/com/yorijori/foodcode/service/BoardService.java
- src/main/java/com/yorijori/foodcode/service/BoardServiceImpl.java
- src/main/java/com/yorijori/foodcode/service/MemberService.java
- src/main/java/mapper/board.xml
- src/main/resources/templates/thymeleaf/board/read.html
- src/main/resources/templates/thymeleaf/board/reply.html
> comment mybatis로 바꾸는 작업 진행 수정 더 필요  board delete

- src/main/java/com/yorijori/foodcode/controller/MemberController.java
- src/main/java/com/yorijori/foodcode/jpa/entity/Category.java
- src/main/java/com/yorijori/foodcode/jpa/entity/UserInfo.java
- src/main/java/com/yorijori/foodcode/jpa/repository/CategoryRepository.java
- src/main/java/com/yorijori/foodcode/repository/CategoryDAO.java
- src/main/java/com/yorijori/foodcode/repository/CategoryDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/CategoryService.java
- src/main/java/com/yorijori/foodcode/service/CategoryServiceImpl.java
- src/main/resources/templates/thymeleaf/member/signUpForm2.html
> 회원가입 페이지 수정

- src/main/java/com/yorijori/foodcode/controller/BoardController.java
- src/main/java/com/yorijori/foodcode/dto/BoardDTO.java
- src/main/java/com/yorijori/foodcode/jpa/entity/Board.java
- src/main/java/com/yorijori/foodcode/jpa/repository/BoardRepository.java
- src/main/java/com/yorijori/foodcode/repository/BoardCommentDAO.java
- src/main/java/com/yorijori/foodcode/repository/BoardCommentDAOImpl.java
- src/main/java/com/yorijori/foodcode/repository/BoardDAO.java
- src/main/java/com/yorijori/foodcode/repository/BoardDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/BoardCommentService.java
- src/main/java/com/yorijori/foodcode/service/BoardCommentServiceImpl.java
- src/main/java/com/yorijori/foodcode/service/BoardService.java
- src/main/java/com/yorijori/foodcode/service/BoardServiceImpl.java
- src/main/java/mapper/board.xml
- src/main/resources/templates/thymeleaf/board/list.html
- src/main/resources/templates/thymeleaf/board/read.html
- src/main/resources/templates/thymeleaf/board/reply.html
- src/main/resources/templates/thymeleaf/board/write.html
> 대댓글 뷰에 뿌리기 성공 ㅠ 조회수 count추가

- src/main/java/com/yorijori/foodcode/controller/MyPageController.java
- src/main/java/com/yorijori/foodcode/controller/RecipeController.java
- src/main/java/com/yorijori/foodcode/repository/IngredientDAOImpl.java
- src/main/resources/static/common/css/recipe/recipeInsert.css
- src/main/resources/static/common/js/recipe/recipe.js
- src/main/resources/templates/thymeleaf/mypage/my_user_info.html
- src/main/resources/templates/thymeleaf/recipe/recipeInsert.html
recipe Insert view 단 수정 및 js 추가
> recipeInsert

- src/main/java/com/yorijori/foodcode/controller/MemberController.java
- src/main/java/com/yorijori/foodcode/controller/RecipeController.java
- src/main/java/com/yorijori/foodcode/jpa/entity/Recipe.java
- src/main/java/com/yorijori/foodcode/jpa/repository/RecipeImageRepository.java
- src/main/java/com/yorijori/foodcode/jpa/repository/RecipeRepository.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAO.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/RecipeService.java
- src/main/java/com/yorijori/foodcode/service/RecipeServiceImpl.java
- src/main/resources/templates/thymeleaf/member/signUpForm2.html
- src/main/resources/templates/thymeleaf/recipe/recipelist.html
- src/main/resources/templates/thymeleaf/recipe/recipeview.html
> 1. 게시물에 대한 정보 가져오는 코드 작성
- 게시물 내용
- 사용자 이름
- 게시물 이미지
- 좋아요 처리
> 2. 오류 고생으로 시간이 오래걸림...내일 할것
- Q/A
- 댓글
- 정보 가져온 내용들 View에 뿌리기
- 테스트용 데이터 [gogledrive](https://drive.google.com/file/d/1jccnMeVUr-EmR5ZD0VnXUnsFCIHyiXe-/view?usp=drive_link)
> 게시물에 대한 정보 가져오는 코드 작성

- pom.xml
- src/main/java/com/yorijori/foodcode/common/RecipeSpecification.java
- src/main/java/com/yorijori/foodcode/controller/RecipeController.java
- src/main/java/com/yorijori/foodcode/dto/FilterDTO.java
- src/main/java/com/yorijori/foodcode/jpa/repository/RecipeRepository.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAO.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/RecipeService.java
- src/main/java/com/yorijori/foodcode/service/RecipeServiceImpl.java
- src/main/resources/templates/thymeleaf/recipe/recipelist.html
너무힘들어요 다중조건..
(미완성) 조건 검색 추가	
- ajax 처리
- view 미처리
- ajax으로 데이터 받아서 필터링에 맞게 검색 (미완성)
> (미완성) 조건 검색 추가 JPA Specification 사용하여 다중 조건 검색 구현

- src/main/java/com/yorijori/foodcode/common/RecipeSpecification.java
- src/main/java/com/yorijori/foodcode/controller/RecipeController.java
- src/main/java/com/yorijori/foodcode/dto/FilterDTO.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAO.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/RecipeService.java
- src/main/java/com/yorijori/foodcode/service/RecipeServiceImpl.java
- src/main/resources/templates/thymeleaf/recipe/recipelist.html
무한 if 필터검색
- ajax으로 view 뿌리는 작업 미완성
- 필터링 추가할 거 더 있음
오늘안에 작업 마무리
> 무한 if 필터검색

- src/main/java/com/yorijori/foodcode/controller/MyPageController.java
- src/main/java/com/yorijori/foodcode/jpa/entity/Category.java
- src/main/java/com/yorijori/foodcode/repository/ProfileDAO.java
- src/main/java/com/yorijori/foodcode/repository/ProfileDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/ProfileService.java
- src/main/java/com/yorijori/foodcode/service/ProfileServiceImpl.java
- src/main/resources/static/common/css/mypage/my_user_info.css
- src/main/resources/static/common/js/mypage/userinfo.js
- src/main/resources/templates/thymeleaf/mypage/changepass.html
- src/main/resources/templates/thymeleaf/mypage/changephoto.html
- src/main/resources/templates/thymeleaf/mypage/my_user_info.html
- src/main/resources/templates/thymeleaf/recipe/recipeInsert.html
> 프로필 부분 css추가 및 선호식품 , 처리 및 값 불러오기 db에 업데이트 완료

- src/main/java/com/yorijori/foodcode/controller/AdminController.java
- src/main/java/com/yorijori/foodcode/controller/RecipeController.java
- src/main/java/com/yorijori/foodcode/jpa/repository/MemberRepository.java
- src/main/java/com/yorijori/foodcode/repository/MemberDAO.java
- src/main/java/com/yorijori/foodcode/repository/MemberDAOImpl.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAO.java
- src/main/java/com/yorijori/foodcode/repository/RecipeDAOImpl.java
- src/main/java/com/yorijori/foodcode/service/MemberService.java
- src/main/java/com/yorijori/foodcode/service/MemberServiceImpl.java
- src/main/java/com/yorijori/foodcode/service/RecipeService.java
- src/main/java/com/yorijori/foodcode/service/RecipeServiceImpl.java
- src/main/resources/templates/thymeleaf/admin/AdminUserPage.html
- src/main/resources/templates/thymeleaf/recipe/recipelist.html
> 평점 List 추가

- src/main/java/com/yorijori/foodcode/controller/BoardController.java
- src/main/java/com/yorijori/foodcode/dto/BoardDTO.java
- src/main/java/mapper/board.xml
- src/main/resources/static/common/css/board/reply.css
- src/main/resources/static/common/css/customerService/insert.css
- src/main/resources/templates/thymeleaf/board/reply.html
- src/main/resources/templates/thymeleaf/board/write.html
- src/main/resources/templates/thymeleaf/customerService/helpInsert.html
- src/main/resources/templates/thymeleaf/customerService/helpList.html
- src/main/resources/templates/thymeleaf/customerService/notiInsert.html
- src/main/resources/templates/thymeleaf/customerService/notificationList.html
reply에 imgpath 코드 맞는 지 확인 한 번 부탁드립니다~!
> 게시판 댓글 문의 수정
